server:
  port: 8080

spring:
  application:
    name: consul-order-service
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}